/**
 * Semantic icon resolution. Explicit per-entity maps for industries / products /
 * blog clusters, plus a bilingual keyword resolver for free-form card copy
 * (benefits, features, use cases, automations, comparison features…).
 * Icon names must exist in components/ui/Icon.tsx.
 */

export const INDUSTRY_ICON: Record<string, string> = {
  "marketing-agencies": "megaphone",
  "real-estate": "building",
  clinics: "stethoscope",
  "car-dealerships": "car",
  saas: "cloud",
  education: "graduation-cap",
  "professional-services": "briefcase",
  veterinary: "paw",
  "pet-grooming": "scissors",
  "call-centers": "headset",
  "dental-clinics": "tooth",
  aesthetics: "gem",
  "home-services": "wrench",
  insurance: "umbrella",
  gyms: "dumbbell",
  restaurants: "utensils",
  "law-firms": "scale",
  physiotherapy: "activity",
};

export const PRODUCT_ICON: Record<string, string> = {
  "ai-crm": "bot",
  "ai-voice-agents": "mic",
  "ai-calling": "phone-outbound",
  "sales-automation": "bolt",
  "lead-management": "filter",
  "growth-marketing-crm": "trending-up",
  "email-marketing": "mail",
  "whatsapp-crm": "whatsapp",
  "sales-proposals": "clipboard",
  "sales-analytics": "chart-line",
  "prospect-finder": "search",
  "landing-pages": "template",
};

export const CLUSTER_ICON: Record<string, string> = {
  "ai-crm": "bot",
  "voice-agents": "mic",
  "sales-automation": "bolt",
  whatsapp: "whatsapp",
  growth: "trending-up",
  guides: "book",
};

/** Ordered keyword → icon rules. First substring match wins, so put the most
 * specific rules first. Keywords are matched case-insensitively (unaccented). */
const KEYWORD_RULES: [string[], string][] = [
  [["whatsapp"], "whatsapp"],
  [["email", "correo", "e-mail", "mail", "bandeja", "inbox"], "mail"],
  [["outbound", "en frio", "en frío", "cold", "saliente", "llamada saliente"], "phone-outbound"],
  [["inbound", "entrante", "recepcion", "recepción", "recibe llamad", "contesta llamad", "atiende llamad"], "phone-incoming"],
  [["transcri", "grabacion", "grabación", "graba la", "voz natural", "por voz", "voicebot", "agente de voz"], "mic"],
  [["llamad", "call", "telefon", "teléfon", "marca", "voz", "voice", "phone"], "phone"],
  [["multicanal", "multichannel", "omnicanal", "varios canales", "cada canal", "por canal"], "layers"],
  [["cita", "agenda", "agend", "reserva", "book a", "reunion", "reunión", "visita", "demo agendada"], "calendar-check"],
  [["recordatorio", "reminder", "no-show", "no show", "aviso"], "bell"],
  [["seguimiento", "follow-up", "follow up", "secuencia", "cadencia", "nurtur", "reactiv", "recupera", "winback", "win-back"], "refresh"],
  [["plantilla", "template", "reutiliz", "reusable", "guarda"], "template"],
  [["automatiz", "disparador", "trigger", "flujo", "flow", "sin programar", "sin codigo", "sin código", "no-code", "workflow"], "bolt"],
  [["asigna", "assign", "distribu", "reparto", "routing", "route", "territorio", "round robin", "round-robin", "carga de trabajo"], "route"],
  [["integr", "conect", "connect", " api", "sincron", "sync", "webhook", "en tu crm", "al crm"], "workflow"],
  [["califica", "scoring", "score", "qualif", "prioriza", "priori", "filtr", "segment", "clasifica"], "filter"],
  [["propuesta", "proposal", "cotiz", "presupuesto", "quote", "documento"], "clipboard"],
  [["ingreso", "revenue", "factura", "cierre", "cerrar", " deal", "close", "compra", "ventas cerradas", "retorno"], "coin"],
  [["conversion", "conversión", "tasa", " rate", "porcentaje", "%", "uplift"], "percent"],
  [["informe", "report", "analit", "analít", "analytic", "metric", "métrica", "dashboard", "panel", "kpi", "dato", "insight", "medici", "medir", "mide"], "chart-bar"],
  [["crece", "crecim", "growth", "escala", "escalar", "scale", "expand", "mas leads", "más leads", "aumenta"], "trending-up"],
  [["cumplimiento", "compliance", "consent", "rgpd", "gdpr", "normativa", "dnc", "robinson", "no-llamar", "no llamar", "privacid", "proteccion de datos", "protección de datos", "opt-in", "opt in"], "shield-check"],
  [["segur", "secur", "cifrad", "encrypt", "protege", "auditor"], "shield"],
  [["control humano", "supervis", "revision", "revisión", "aprueba", "aprob", "handoff", "hand-off", "traspaso", "a una persona", "agente humano", "toque humano"], "user-check"],
  [["idioma", "lengua", "language", "multiidioma", "cada mercado", "mercado", "pais", "país", "global", "internacional", "geograf"], "globe"],
  [["equipo", "team", "comercial", "vendedor", "rep ", "representante", "agente", "colaborador"], "users"],
  [["cliente", "customer", "lead", "contacto", "prospecto", "comprador", "paciente"], "user-check"],
  [["objecion", "objeción", "objection", "guion", "guión", "script", "conversa", "chat", "mensaj", "responde"], "message"],
  [["inteligencia", "chatbot", "voicebot", "asistente", "asesor", "entren", "aprende de", "modelo de ia", " con ia", " de ia", " por ia", "agente de ia"], "bot"],
  [["24", "hora", "hour", "tiempo", "time", "instant", "rapid", "rápid", "speed", "minuto", "al momento", "en segundos", "sin esperar"], "clock"],
  [["busqueda", "búsqueda", "search", "encuentra", "descubr", "detecta"], "search"],
  [["objetivo", "meta ", "target", "goal", "foco"], "target"],
  [["consisten", "estandar", "estándar", "standard", "proceso", "process", "estructur", "orden", "checklist", "paso a paso"], "list-checks"],
  [["menos", "reduc", "ahorr", "save", "elimina", "evita", "deja de"], "sparkles"],
  [["valor", "value", "premium", "vip", "alto"], "star"],
];

function normalize(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "");
}

/** Resolve a free-form card title/label to an icon name. */
export function iconForText(text: string, fallback = "sparkles"): string {
  const t = normalize(text);
  // Verified per-string overrides win over the keyword heuristic.
  const override = TEXT_ICON_OVERRIDE[t];
  if (override) return override;
  // Standalone "IA" / "AI" labels (e.g. a flow chip) map straight to the bot glyph.
  if (t === "ia" || t === "ai") return "bot";
  for (const [keywords, icon] of KEYWORD_RULES) {
    for (const kw of keywords) {
      if (t.includes(normalize(kw))) return icon;
    }
  }
  return fallback;
}

/** Resolve an industry display name (home grid uses names, not ids). */
export function iconForIndustry(name: string): string {
  const t = normalize(name);
  const map: [string, string][] = [
    ["veterinar", "paw"],
    ["peluquer", "scissors"],
    ["mascota", "paw"],
    ["dental", "tooth"],
    ["clinic", "stethoscope"],
    ["fisio", "activity"],
    ["estetic", "gem"],
    ["belleza", "gem"],
    ["inmobili", "building"],
    ["concesionar", "car"],
    ["coche", "car"],
    ["auto", "car"],
    ["agencia", "megaphone"],
    ["marketing", "megaphone"],
    ["saas", "cloud"],
    ["educ", "graduation-cap"],
    ["formaci", "graduation-cap"],
    ["academ", "graduation-cap"],
    ["call center", "headset"],
    ["contact center", "headset"],
    ["telemarketing", "headset"],
    ["seguro", "umbrella"],
    ["gimnas", "dumbbell"],
    ["fitness", "dumbbell"],
    ["restaurant", "utensils"],
    ["hosteler", "utensils"],
    ["abogad", "scale"],
    ["despacho", "scale"],
    ["legal", "scale"],
    ["reforma", "wrench"],
    ["hogar", "wrench"],
    ["servicios prof", "briefcase"],
    ["servicio", "briefcase"],
    ["consultor", "briefcase"],
  ];
  for (const [kw, icon] of map) {
    if (t.includes(kw)) return icon;
  }
  return "briefcase";
}

/* Verified icon overrides — from adversarial audit of 907 card strings (260 corrections). */
export const TEXT_ICON_OVERRIDE: Record<string, string> = {
  "\"due for a groom\" heads-up to recurring clients based on their pet's frequency": "refresh",
  "agendado de la llamada con el agente humano con el aviso de ia y el consentimiento registrados": "calendar-check",
  "ai advisor trained in your niche": "bot",
  "ai agent language": "languages",
  "ai answers": "bot",
  "alertas automaticas cuando una cuenta alcanza limites de uso": "bell",
  "alta": "user-plus",
  "amplitud de la suite comercial": "layers",
  "answering common questions about hours, location, menu, or set menus": "message",
  "appointment": "calendar-check",
  "appointment booking": "calendar-check",
  "appointment reminders to reduce no-shows and recover gaps that fall through": "calendar",
  "appointment scheduling": "calendar-check",
  "atencion de llamadas y whatsapp mientras el equipo esta tratando, fuera de horario o cuando la recepcion esta ocupada": "filter",
  "ausencias y citas que se caen": "bell",
  "automatic ai response to inbound calls and messages": "bot",
  "automatic alerts when an account hits usage limits": "bell",
  "automatic booking of trial classes or facility visits": "calendar-check",
  "automatic delivery of course information, pricing, and dates": "send",
  "automatic distribution of inbound leads across sales reps": "route",
  "automatic list dialing with a per-campaign qualification script": "phone",
  "automatic no-show recovery and follow-up on open estimates": "refresh",
  "automatic qualification of each inbound inquiry with a priority score": "filter",
  "automatic re-engagement of no-shows to rebook the lost slot": "refresh",
  "automatic scheduling of in-person or virtual visits": "calendar-check",
  "bandeja de conversaciones unificada": "inbox",
  "base de datos unificada de leads y clientes": "user-check",
  "behavior-based automations": "bolt",
  "beyond chatting on whatsapp, your team needs to call: answer inbound calls instantly and make outbound ones, including cold campaigns at volume.": "phone",
  "book": "calendar-check",
  "book visit": "calendar-check",
  "booking": "calendar-check",
  "booking and rescheduling of recurring appointments based on the center's availability": "calendar-check",
  "booking appointments by size, breed, and service type to estimate the right duration": "calendar-check",
  "booking by size, breed, and service with the estimated duration of each appointment": "calendar-check",
  "booking demos for accounts showing high-interest signals": "calendar-check",
  "booking the call with the human agent, with the ai disclosure and consent on record": "calendar-check",
  "booking the first consultation with the right attorney or practice area": "calendar-check",
  "bottleneck identification": "chart-bar",
  "breadth of the sales suite": "layers",
  "buscas un precio de voz por minuto transparente en vez de un billing apilado y dificil de anticipar.": "coin",
  "buscas una suite mas amplia de serie (voz + whatsapp + email + propuestas + crm) en lugar de ensamblar mensajeria con varias apps del marketplace.": "layers",
  "businesses looking to reduce the time between a lead arriving and first contact": "clock",
  "calidad de voz y latencia": "waveform",
  "calificacion automatica de cada consulta entrante con score de prioridad": "filter",
  "calificacion del motivo de contacto (urgencia, primera visita, revision, presupuesto) antes de agendar": "filter",
  "calificacion inicial de leads entrantes antes de pasarlos a un ejecutivo de ventas": "filter",
  "campaign and sequence editor": "refresh",
  "campaign overflow during volume spikes": "headset",
  "campanas de seguimiento a clientas recurrentes con promociones y recordatorios de repeticion": "refresh",
  "cancellations and inactive members left alone": "refresh",
  "channel and campaign comparison": "chart-bar",
  "channel-level return reporting": "coin",
  "clase de prueba": "calendar-check",
  "clientes recurrentes que se pierden el ritmo": "refresh",
  "collecting group and event details and handing them to a person with the information summarized": "handshake",
  "companies expanding internationally that want to standardize their sales process across markets": "globe",
  "companies receiving leads from multiple channels that need a single management point": "layers",
  "comparacion de canales y campanas": "chart-bar",
  "comparacion de rendimiento entre canales de adquisicion o campanas": "chart-bar",
  "comparing performance across acquisition channels or campaigns": "chart-bar",
  "confirmacion": "check-circle",
  "confirmation": "check-circle",
  "confirming and rescheduling sales appointments": "calendar-check",
  "consulta": "message",
  "consultas de matricula sin respuesta rapida": "bell",
  "coste total de propiedad": "coin",
  "crm and pipeline": "chart-bar",
  "crm and sales pipeline": "chart-bar",
  "crm y pipeline": "chart-bar",
  "crm y pipeline de ventas": "chart-bar",
  "cualificacion de leads": "filter",
  "data export": "send",
  "demo": "play",
  "desbordamiento (overflow) de campanas en picos de volumen": "headset",
  "deteccion de oportunidades de upsell y renovacion": "search",
  "detecting upsell and renewal opportunities": "search",
  "distribucion automatica de leads entrantes entre representantes comerciales": "route",
  "el primero en contestar se lleva el trabajo": "clock",
  "encuestas rapidas de satisfaccion o intencion de compra despues de una interaccion": "message",
  "end-to-end visibility": "chart-bar",
  "enrollment inquiries without a fast response": "clock",
  "enrutamiento de oportunidades al account manager correcto segun cuenta o servicio": "route",
  "enrutamiento del asunto al area o abogado adecuado segun lo identificado por la ia": "route",
  "envio automatico de informacion de cursos, precios y fechas": "send",
  "equipos comerciales que buscan reducir el tiempo de respuesta al primer contacto": "clock",
  "faster responses": "clock",
  "field teams that can't pick up the phone": "clock",
  "filtering out cases that fall outside the firm's practice areas or aren't viable": "clipboard",
  "financiacion": "coin",
  "financing": "coin",
  "financing and paperwork slow down closing": "coin",
  "follow-up campaigns to recurring clients with promotions and repeat-treatment reminders": "refresh",
  "following up on inquiries that stalled early on": "refresh",
  "following up on sent quotes that haven't received a reply yet": "refresh",
  "following up with leads comparing prices before deciding": "refresh",
  "full pipeline visibility": "chart-bar",
  "full traceability": "search",
  "gaps and overlaps in the schedule": "calendar",
  "groups and events that eat up time": "calendar",
  "growth teams that need to coordinate with the sales team": "users",
  "handing group and event requests to a person with the collected detail": "handshake",
  "handling calls and whatsapp while the team is treating, after hours, or when the front desk is busy": "filter",
  "handoff": "handshake",
  "handoff / booking": "calendar-check",
  "historial unificado de interacciones": "message",
  "human agent": "user-check",
  "human control": "user-check",
  "ia contesta": "bot",
  "identificacion de cuellos de botella": "chart-bar",
  "identificacion de interes en financiacion y vehiculo de entrega": "coin",
  "identificacion de la etapa del pipeline donde se pierden mas oportunidades": "chart-bar",
  "identifying interest in financing and trade-in vehicles": "user-check",
  "identifying the pipeline stage where most opportunities are lost": "chart-bar",
  "identifying the reason (urgent, vaccine, check-up, grooming, surgery) before booking": "filter",
  "immediate contact": "clock",
  "immediate response to inquiries about programs, courses, or scholarships": "clock",
  "informes de rendimiento de leads por cliente para reuniones de reporting": "chart-bar",
  "initial qualification of inbound leads before handing them to a sales rep": "filter",
  "inquiry": "message",
  "list": "list-checks",
  "lista": "list-checks",
  "low-friction scheduling": "calendar-check",
  "marketing decisions backed by sales data": "chart-bar",
  "mensaje o llamada de bienvenida en cuanto entra un lead de campana": "user-plus",
  "messages coordinated across channels": "layers",
  "metricas conectadas al crm": "chart-bar",
  "metrics connected to the crm": "chart-bar",
  "missed visits": "bell",
  "modelo de precios": "coin",
  "motivo": "message",
  "muchos leads, pocos compradores reales": "user-check",
  "naturaleza del producto": "bot",
  "nature of the product": "tag",
  "necesidad de programar": "bolt",
  "necesitas el control humano y el cumplimiento (aviso de ia, consentimiento, proteccion de datos de cada pais) como parte del planteamiento comercial, no como un anadido.": "shield-check",
  "need to code": "bolt",
  "negocios que quieren reducir el tiempo entre la llegada del lead y el primer contacto": "clock",
  "no-shows and gaps that go unfilled": "refresh",
  "no-shows que vacian la agenda": "calendar",
  "no-shows that empty the schedule": "calendar",
  "no-shows y huecos que no se rellenan": "refresh",
  "notificacion al equipo comercial ante senales de intencion de upgrade": "bell",
  "omnichannel messaging": "layers",
  "open and status tracking": "chart-bar",
  "organizations wanting to avoid duplicate or uncoordinated repeat contacts": "user-check",
  "overloaded front desk and clients who don't return": "headset",
  "pre-qualification call or message as soon as a quote request comes in": "user-check",
  "precio de la voz": "tag",
  "presupuestos que se pierden sin seguimiento": "clipboard",
  "presupuestos y venta cruzada que quedan olvidados": "refresh",
  "pricing model": "tag",
  "primera consulta": "calendar-check",
  "proposal delivery or meeting scheduling once a lead qualifies": "calendar-check",
  "pruebas de manejo sin confirmar": "calendar-check",
  "puntuacion de leads con ia": "filter",
  "qualification message or call when the trial starts": "search",
  "qualifying the reason for contact (first visit, follow-up, podiatry checkup, package session) before booking": "calendar-check",
  "quick satisfaction or purchase-intent surveys after an interaction": "message",
  "quieres agentes de voz ia nativos (no solo un click-to-call ni una integracion de telefonia de terceros) que califiquen y agenden por telefono.": "mic",
  "quieres que tu equipo humano mantenga el control y que el cumplimiento (aviso de ia, consentimiento, rgpd) sea visible, no un anadido.": "refresh",
  "quote requests that go cold": "refresh",
  "quotes and cross-sell left forgotten": "clock",
  "quotes lost without follow-up": "phone-incoming",
  "re-engagement campaigns for inactive customers or leads": "refresh",
  "re-engagement campaigns for inactive members who haven't attended in weeks": "refresh",
  "re-engagement flows for opportunities stalled at a pipeline stage": "refresh",
  "re-engagement of leads who showed interest but didn't enroll": "refresh",
  "re-engagement of older leads that never closed": "refresh",
  "re-engagement of sent quotes that went unanswered": "refresh",
  "re-engaging leads that have gone unanswered for a while": "refresh",
  "re-engaging recurring clients with a heads-up that their pet is due for a groom": "refresh",
  "reason": "message",
  "recepcion saturada y clientas que no vuelven": "headset",
  "recontacto de leads que llevan tiempo sin respuesta": "refresh",
  "recopilacion de datos de grupos y eventos y traspaso a una persona con la informacion resumida": "handshake",
  "recordatorios automaticos de citas para reducir ausencias": "bell",
  "recovering missed appointments and prompting booster vaccines and due check-ups": "refresh",
  "recovery and reactivation of cold databases": "refresh",
  "recuperacion automatica de no-shows y seguimiento de presupuestos sin cerrar": "refresh",
  "recuperacion de bajas con una oferta o llamada de seguimiento a tiempo": "refresh",
  "recurring clients who lose the rhythm": "refresh",
  "reenganche a leads que mostraron interes pero no se inscribieron": "refresh",
  "reenganche de leads antiguos que quedaron sin cerrar": "refresh",
  "reenganche de presupuestos enviados que quedaron sin respuesta": "refresh",
  "registro unificado": "list-checks",
  "renewal reminders and notices by voice, whatsapp, and email before expiration": "bell",
  "renovaciones y avisos sin seguimiento a tiempo": "refresh",
  "rep-level performance tracking": "gauge",
  "reportes de retorno por canal": "chart-bar",
  "reportes por canal de origen": "chart-bar",
  "request": "clipboard",
  "reservas que se pierden en horas de servicio": "calendar",
  "respecting permitted calling hours, consent and exclusion lists": "shield-check",
  "response automations": "bolt",
  "respuesta a dudas frecuentes de horarios, ubicacion, carta o menus cerrados": "message",
  "respuesta inmediata a consultas sobre programas, cursos o becas": "clock",
  "results tracked in one place": "chart-bar",
  "sales teams looking to reduce response time to first contact": "clock",
  "scaling volume without exploding costs": "trending-up",
  "schedule": "calendar",
  "scheduling and confirming test drives": "calendar-check",
  "scheduling and rescheduling appointments based on availability": "calendar-check",
  "scheduling and rescheduling appointments based on each physiotherapist's or podiatrist's availability": "refresh",
  "scheduling and rescheduling appointments based on each provider's or operatory's availability": "calendar-check",
  "scheduling site visits and confirming them with reminders to cut no-shows": "calendar-check",
  "segmentation based on real crm data": "filter",
  "seguimiento de indicadores individuales para sesiones de coaching comercial": "chart-bar",
  "seguimiento de presupuestos con recordatorios espaciados hasta obtener respuesta": "filter",
  "seguimiento de resultados en un solo lugar": "chart-bar",
  "seguimiento del desempeno por representante": "gauge",
  "sending an initial proposal or scheduling a meeting based on the score": "calendar-check",
  "service and pricing inquiries without a fast response": "clock",
  "session-package follow-up and automatic no-show recovery to rebook": "target",
  "session-package tracking: reminding patients of remaining sessions and offering a date to complete them": "calendar-check",
  "sign-up": "user-plus",
  "site visit": "calendar-check",
  "smart summaries": "bot",
  "solicitud": "clipboard",
  "surfacing cross-sell opportunities across lines for the human agent": "coin",
  "test drive": "car",
  "time lost on cases that don't fit": "calendar-check",
  "total cost of ownership": "coin",
  "transferencia a un tecnico o comercial en cuanto hay interes real de contratar": "handshake",
  "traspaso a una persona de las solicitudes de grupos y eventos con el detalle recopilado": "handshake",
  "tratamientos de alto valor que no se cierran": "coin",
  "trial class": "calendar-check",
  "trial class or visit booking with automatic confirmation and reminder": "calendar-check",
  "trial classes and visits that never happen": "calendar-check",
  "trials que no se convierten": "coin",
  "trials that don't convert": "percent",
  "tu equipo comercial prioriza la velocidad de puesta en marcha frente a la personalizacion extrema.": "clock",
  "unconfirmed test drives": "calendar-check",
  "uncoordinated scheduling": "calendar-check",
  "unfollowed informational inquiries": "refresh",
  "unified call logging": "list-checks",
  "unified conversation inbox": "inbox",
  "unified funnel from acquisition to close": "filter",
  "unified interaction history": "message",
  "upgrade": "trending-up",
  "valoras una ia que se comporte como un asesor de tu nicho y una suite integrada (voz + whatsapp + email + propuestas + crm) mas que abarcar el maximo de redes de chat.": "chart-bar",
  "valoras una ia que se comporte como un asesor de tu nicho, con el equipo humano al control y el cumplimiento (aviso de ia, consentimiento, proteccion de datos) siempre visible.": "shield-check",
  "visibilidad completa del pipeline": "chart-bar",
  "visibilidad de extremo a extremo": "chart-bar",
  "voice pre-qualification before passing the lead to a human agent": "mic",
  "voice pricing": "coin",
  "warm transfer to a human agent when there is interest": "user-check",
  "welcome message or call the moment a campaign lead comes in": "user-plus",
  "welcome sequences for new leads entering the crm": "user-plus",
  "white-label and reselling": "tag",
  "you do not need a long implementation project to start automating sales.": "bolt",
  "you sell in spanish (spain or latam) and need the ai to answer and qualify in your customers' language, not only in english.": "globe",
  "you want a broader suite out of the box (voice + whatsapp + email + proposals + crm) instead of stitching messaging together with several marketplace apps.": "layers",
  "you want a crm focused specifically on sales, rather than one module inside a broader suite.": "target",
  "you want a product ready to sell, not to build one: you would rather start answering, qualifying and booking today than spend weeks of development assembling an agent.": "calendar-check",
  "you want native ai voice agents (not just click-to-call or a third-party telephony integration) that qualify and book by phone.": "mic",
  "you want transparent per-minute voice pricing instead of stacked billing that is hard to anticipate.": "coin",
  "your priority is not losing opportunities by failing to respond in time: speed-to-lead, after hours and recovering missed appointments.": "refresh",
  "your sales team prioritizes speed to launch over extreme customization.": "clock",
  "your team works in spanish (spain or latam) and you want the ai to answer and qualify in your customers' language, not on a platform built for english first.": "languages",
};
