const assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');const {req,stores,actor}=require('./assistantWorkflowFixture.cjs');
const w=req('./src/services/assistantWorkflows.ts'),r=req('./src/services/assistantRoutines.ts');
(async()=>{const app=req('fastify')();await app.register(req('@fastify/jwt'),{secret:'isolated-objective-tests-secret'});for(const [path,file,name]of[['/api/assistant','platformAssistant','platformAssistantRoutes'],['/api/assistant','assistantWorkflows','assistantWorkflowRoutes'],['/api/assistant','assistantRoutines','assistantRoutinesRoutes'],['/api/tasks','tasks','tasksRoutes'],['/api/leads','leads','leadsRoutes']])await app.register(req('./src/routes/'+file+'.ts')[name],{prefix:path});await app.ready();
const headers={authorization:'Bearer '+app.jwt.sign({...actor,tokenType:'access',sessionId:'qa-session'})};const call=async(url,payload,method='POST')=>{const response=await app.inject({method,url,headers,...(payload?{payload}:{})});assert.equal(response.statusCode,200,response.body);return response.json()};
const input={objective:'Encuentra peluquerías y prepara seguimiento',target:'Peluquerías',location:'Madrid',kind:'clients',source:'saved',maxResults:5,maxSearches:4,followUp:true,allowExternalReview:false,requestId:randomUUID()};
let run=(await call('/api/assistant/runs',input)).run;assert.equal((await call('/api/assistant/runs',input)).run.id,run.id);for(let i=0;i<5&&run.status!=='review';i++){run=(await call('/api/assistant/runs/'+run.id+'/advance',{})).run;console.log(run.status,run.revision,run.error||'');}
assert.equal(run.status,'review');assert.equal(run.candidates.length,2);assert.equal(run.candidates[0].duplicateLeadId,'qa-existing');assert(run.context.services.some(s=>s.priceCents===6000));
run=(await call('/api/assistant/runs/'+run.id+'/review',{revision:run.revision,items:run.candidates.map(c=>({candidateId:c.id,name:c.name,company:c.company,selected:true,taskTitle:'Validar '+c.name}))})).run;
let applied=await call('/api/assistant/runs/'+run.id+'/apply',{revision:run.revision});assert.equal(applied.run.status,'completed',JSON.stringify(applied));assert.equal(stores.lead.length,2);assert.equal(stores.task.length,2);await call('/api/assistant/runs/'+run.id+'/apply',{revision:run.revision});assert.equal(stores.lead.length,2);
const undo=applied.actions.find(a=>a.name==='create_task');await call('/api/assistant/actions/'+undo.id+'/undo',{});assert.equal(stores.task[0].status,'cancelled');
const refreshed=(await call('/api/assistant/runs/'+run.id,undefined,'GET')).run;
assert.equal(refreshed.actions.find(action=>action.id===undo.id).undoAvailable,false);
assert.equal(refreshed.actions.find(action=>action.id===undo.id).undoStatus,'completed');
const changedTask=applied.actions.filter(action=>action.name==='create_task')[1];
stores.task.find(task=>task.id===changedTask.result.id).updatedAt=new Date(Date.now()+10000);
const refused=await app.inject({method:'POST',url:'/api/assistant/actions/'+changedTask.id+'/undo',headers,payload:{}});
assert.equal(refused.statusCode,409);assert.equal(stores.task.find(task=>task.id===changedTask.result.id).status,'open');
const routine=await call('/api/assistant/routines',{name:'Revisar cada semana',input:{...input,requestId:randomUUID()},intervalHours:168,startsAt:new Date(Date.now()+3600000).toISOString(),maxRuns:1,requestId:randomUUID()});const manualId=randomUUID();const result=await call('/api/assistant/routines/'+routine.id+'/run',{requestId:manualId});assert(result.run.id);await call('/api/assistant/routines/'+routine.id+'/run',{requestId:manualId});
for(let i=1;i<=5;i++)await r.dispatchAssistantRoutines(new Date(Date.now()+i*120000));const routines=await r.listAssistantRoutines(actor);assert.equal(routines[0].runCount,1);assert.equal(routines[0].status,'completed');assert.equal(stores.lead.length,2);assert.equal(stores.task.length,2);assert.equal((await r.listAssistantNotifications(actor)).length,1);await r.dispatchAssistantRoutines(new Date(Date.now()+10*86400000));assert.equal((await r.listAssistantNotifications(actor)).length,1);console.log('PASS full workflow, review, apply, undo, recurrence counters and notifications');await app.close()})().catch(e=>{console.error(e);process.exitCode=1});
