const {createRequire}=require('node:module');
const req=createRequire(require('node:path').resolve(__dirname, '../../package.json')); req('tsx/cjs');
process.env.NODE_ENV='test'; process.env.BACKGROUND_WORKERS_ENABLED='false';
const {prisma}=req('./src/lib/prisma.ts');
const {Prisma}=req('@prisma/client'); const {randomUUID}=require('node:crypto');
const stores={}; const clone=x=>structuredClone(x); const equal=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
function testValue(value,filter){if(filter===undefined)return true;if(filter===null||typeof filter!=='object'||filter instanceof Date)return equal(value,filter);if(Array.isArray(filter))return equal(value,filter);if(filter.path){const child=filter.path.reduce((v,k)=>v?.[k],value);return testValue(child,Object.fromEntries(Object.entries(filter).filter(([k])=>k!=='path')))}if('equals'in filter)return filter.mode==='insensitive'?String(value).toLowerCase()===String(filter.equals).toLowerCase():equal(value,filter.equals);if('in'in filter)return filter.in.includes(value);if('notIn'in filter)return !filter.notIn.includes(value);if('contains'in filter)return String(value||'').toLowerCase().includes(String(filter.contains).toLowerCase());if('not'in filter)return !testValue(value,filter.not);if('lte'in filter&&!(value<=filter.lte))return false;if('lt'in filter&&!(value<filter.lt))return false;if('gte'in filter&&!(value>=filter.gte))return false;if('gt'in filter&&!(value>filter.gt))return false;if(Object.keys(filter).some(k=>['lte','lt','gte','gt'].includes(k)))return true;return match(value||{},filter)}
function match(row,where={}){return Object.entries(where).every(([key,value])=>key==='AND'?(Array.isArray(value)?value:[value]).every(w=>match(row,w)):key==='OR'?value.some(w=>match(row,w)):key==='NOT'?!match(row,value):!(key in row)&&key.includes('_')?match(row,value):testValue(row[key],value))}
for(const model of Prisma.dmmf.datamodel.models){const name=model.name[0].toLowerCase()+model.name.slice(1);const table=stores[name]=[];const api=prisma[name];if(!api)continue;const update=(row,data)=>{Object.assign(row,clone(data));row.updatedAt=new Date();return clone(row)};api.findMany=async({where={},take,skip=0}={})=>clone(table.filter(row=>match(row,where)).slice(skip,take===undefined?undefined:skip+take));api.findFirst=async({where={}}={})=>clone(table.find(row=>match(row,where))||null);api.findUnique=api.findFirst;api.count=async({where={}}={})=>table.filter(row=>match(row,where)).length;api.create=async({data})=>{const row={id:randomUUID(),createdAt:new Date(),updatedAt:new Date(),...clone(data)};if(name==='lead')row.status||='new';if(name==='task')row.status||='open';table.push(row);return clone(row)};api.updateMany=async({where={},data})=>{const rows=table.filter(row=>match(row,where));rows.forEach(row=>update(row,data));return{count:rows.length}};api.update=async({where,data})=>{const row=table.find(row=>match(row,where));if(!row)throw new Error('Fixture missing '+name);return update(row,data)};api.upsert=async({where,create,update:data})=>{const row=table.find(row=>match(row,where));return row?update(row,data):api.create({data:create})};api.deleteMany=async()=>{throw new Error('Unexpected delete in objective QA')};}
let txQueue=Promise.resolve();prisma.$transaction=(fn)=>{const result=txQueue.then(async()=>{const copy=clone(stores);try{return await fn(prisma)}catch(error){for(const key of Object.keys(stores)){stores[key].splice(0,stores[key].length,...copy[key])}throw error}});txQueue=result.catch(()=>{});return result};
const actor={orgId:'qa-org',userId:'qa-user',role:'owner',workspaceScope:'org'};
stores.organization.push({id:actor.orgId,name:'Salones Software',industry:'Software',plan:'completo',address:'Madrid',currency:'EUR',settings:{businessProfile:{description:'Software para peluquerías',idealCustomer:'Peluquerías',valueProposition:'Gestiona reservas y citas',offers:[{id:'plan',name:'Plan Reservas',description:'Agenda online',priceCents:4900,currency:'EUR',billingPeriod:'monthly',active:true}]}}});
stores.organizationMembership.push({id:'member',orgId:actor.orgId,userId:actor.userId,status:'active',role:'owner'});stores.user.push({id:actor.userId,orgId:actor.orgId,role:'owner',name:'Pruebas'});
stores.lead.push({id:'qa-existing',orgId:actor.orgId,name:'Peluquería Ana',company:'Peluquería Ana',ownerId:actor.userId,status:'new',createdAt:new Date(),updatedAt:new Date()});
stores.microappConfig.push({id:'qa-knowledge',orgId:actor.orgId,microappId:'business-opportunity-radar',scope:'radar-company-profile',scopeId:'default',values:{website:'https://example.com',notes:'Software para peluquerías',services:[{name:'Configuración',description:'Puesta en marcha',priceCents:6000,currency:'EUR',billing:'service'}],sourceIds:['qa-document']},createdAt:new Date(),updatedAt:new Date()},{id:'qa-document',orgId:actor.orgId,microappId:'business-opportunity-radar',scope:'radar-company-source',scopeId:'doc',values:{name:'Catálogo de servicios.pdf',text:'Software de reservas para peluquerías. Configuración 60 EUR.',kind:'pdf',warnings:[]},createdAt:new Date(),updatedAt:new Date()});
stores.microappRun.push({id:'qa-investigation',orgId:actor.orgId,microappId:'business-opportunity-radar',jobId:'qa-job',createdAt:new Date(),input:{radar:{kind:'clients',target:'Peluquerías',location:'Madrid'}},result:{data:{candidates:[{name:'Peluquería Ana',company:'Peluquería Ana',kind:'clients',location:'Madrid',sourceUrl:'https://example.com/ana',sourceTitle:'Peluquería Ana en Madrid',sourceSnippet:'Peluquería Ana en Madrid. Reservas por teléfono.',rationale:'Posible necesidad de reservas online.',detectedAt:new Date().toISOString(),status:'candidate'},{name:'Peluquería Elena',company:'Peluquería Elena',kind:'clients',location:'Madrid',sourceUrl:'https://example.com/elena',sourceTitle:'Peluquería Elena en Madrid',sourceSnippet:'Peluquería Elena ofrece servicios en Madrid.',rationale:'Negocio local del segmento indicado.',detectedAt:new Date().toISOString(),status:'candidate'}]}}});
const initial=clone(stores);function reset(){for(const key of Object.keys(stores))stores[key].splice(0,stores[key].length,...clone(initial[key]));}module.exports={req,prisma,stores,actor,reset};
