/**
 * Catálogo editorial comprometido para la apertura de la plataforma.
 *
 * El número conserva la trazabilidad con la lista aprobada por producto; el
 * `id` es el contrato estable que consumen API, jobs, historial y marketplace.
 */
export const VISION_MICROAPPS = [
  { number: 1, id: 'buying-signal-radar', name: 'Radar de señales de compra' },
  { number: 2, id: 'landing-autopsy', name: 'Autopsia de landing' },
  { number: 3, id: 'creative-fatigue-doctor', name: 'Doctor de fatiga creativa' },
  { number: 4, id: 'abm-account-planner', name: 'Planificador de cuenta ABM' },
  { number: 5, id: 'missed-call-analyzer', name: 'Analizador de llamadas perdidas' },
  { number: 6, id: 'irresistible-offer-builder', name: 'Constructor de oferta irresistible' },
  { number: 7, id: 'full-campaign-generator', name: 'Generador de campaña completa' },
  { number: 8, id: 'sales-meeting-simulator', name: 'Simulador de reunión comercial' },
  { number: 9, id: 'visual-competitive-analyzer', name: 'Analizador competitivo visual' },
  { number: 10, id: 'won-customer-growth-engine', name: 'Convertidor de cliente ganado en crecimiento' },
  { number: 11, id: 'decision-maker-map', name: 'Mapa de decisores' },
  { number: 12, id: 'trigger-event-detector', name: 'Detector de eventos desencadenantes' },
  { number: 13, id: 'explainable-prospect-scoring', name: 'Scoring explicable de prospectos' },
  { number: 14, id: 'negotiation-prep', name: 'Preparador de negociación' },
  { number: 15, id: 'account-political-map', name: 'Mapa político de la cuenta' },
  { number: 16, id: 'commercial-proposal-generator', name: 'Generador de propuesta comercial' },
  { number: 17, id: 'expansion-opportunity-detector', name: 'Detector de oportunidades de expansión' },
  { number: 18, id: 'stalled-deal-rescuer', name: 'Rescatador de oportunidades estancadas' },
  { number: 19, id: 'sector-objection-researcher', name: 'Investigador de objeciones del sector' },
  { number: 20, id: 'seller-coach', name: 'Coach de vendedor' },
  { number: 21, id: 'discovery-question-generator', name: 'Generador de preguntas de descubrimiento' },
  { number: 22, id: 'deal-competitor-detector', name: 'Detector de competidor en una oportunidad' },
  { number: 23, id: 'voice-agent-designer', name: 'Diseñador de agente de voz' },
  { number: 24, id: 'call-compliance-inspector', name: 'Inspector de cumplimiento de llamadas' },
  { number: 25, id: 'call-opening-optimizer', name: 'Optimizador de apertura de llamada' },
  { number: 26, id: 'objection-lab', name: 'Laboratorio de objeciones' },
  { number: 27, id: 'call-emotion-friction-analyzer', name: 'Analizador de emoción y fricción' },
  { number: 28, id: 'post-call-followup-generator', name: 'Creador de follow-up posllamada' },
  { number: 29, id: 'voice-agent-qa', name: 'QA automático de agentes' },
  { number: 30, id: 'ad-angle-miner', name: 'Minería de ángulos publicitarios' },
  { number: 31, id: 'ad-policy-risk-review', name: 'Predicción de políticas publicitarias' },
  { number: 32, id: 'controlled-ad-variants', name: 'Generador de variantes controladas' },
  { number: 33, id: 'ad-to-landing-translator', name: 'Traductor de anuncio a landing' },
  { number: 34, id: 'weak-promise-detector', name: 'Detector de promesas débiles' },
  { number: 35, id: 'ugc-campaign-builder', name: 'Generador de UGC' },
  { number: 36, id: 'multichannel-campaign-adapter', name: 'Adaptador multicanal de campañas' },
  { number: 37, id: 'ad-library-analyzer', name: 'Analizador de biblioteca publicitaria' },
  { number: 38, id: 'form-friction-optimizer', name: 'Optimizador de formularios' },
  { number: 39, id: 'ab-test-hypothesis-designer', name: 'Generador de test A/B con hipótesis' },
  { number: 40, id: 'attribution-repairer', name: 'Reparador de atribución' },
  { number: 41, id: 'authority-report', name: 'Generador de informe de autoridad' },
  { number: 42, id: 'original-study-builder', name: 'Constructor de estudio original' },
  { number: 43, id: 'generic-content-detector', name: 'Detector de contenido genérico' },
  { number: 44, id: 'executive-opinion-engine', name: 'Motor de opinión ejecutiva' },
  { number: 45, id: 'personalized-newsletter-builder', name: 'Creador de newsletter personalizada' },
  { number: 46, id: 'content-refresh-auditor', name: 'Actualizador de contenido antiguo' },
  { number: 47, id: 'commercial-editorial-planner', name: 'Planificador editorial por oportunidad comercial' },
  { number: 48, id: 'sales-asset-generator', name: 'Generador de activos de venta' },
  { number: 49, id: 'virtual-creative-director', name: 'Director creativo virtual' },
  { number: 50, id: 'consented-synthetic-casting', name: 'Casting sintético con consentimiento' },
  { number: 51, id: 'production-continuity-inspector', name: 'Inspector de continuidad' },
  { number: 52, id: 'video-ad-inspector', name: 'Inspector de vídeo publicitario' },
  { number: 53, id: 'studio-broll-generator', name: 'Generador de b-roll' },
  { number: 54, id: 'intelligent-format-adapter', name: 'Adaptador inteligente de formatos' },
  { number: 55, id: 'trailer-cutdown-generator', name: 'Generador de tráileres y cortes' },
  { number: 56, id: 'audiovisual-localizer', name: 'Localizador audiovisual' },
  { number: 57, id: 'product-video-generator', name: 'Generador de vídeo de producto' },
  { number: 58, id: 'blind-provider-comparator', name: 'Comparador ciego de proveedores' },
  { number: 59, id: 'ai-spend-auditor', name: 'Auditor de gasto de IA' },
  { number: 60, id: 'ai-stack-optimizer', name: 'Optimizador de stack' },
  { number: 61, id: 'provider-change-monitor', name: 'Monitor de cambios de proveedores' },
  { number: 62, id: 'declarative-microapp-generator', name: 'Generador de microapps' },
  { number: 63, id: 'flow-auditor', name: 'Auditor de flujos' },
  { number: 64, id: 'ai-cost-simulator', name: 'Simulador de costes' },
  { number: 65, id: 'broken-automation-detector', name: 'Detector de automatizaciones rotas' },
  { number: 66, id: 'client-compliance-pack', name: 'Pack de cumplimiento para clientes' },
] as const

export type VisionMicroappId = (typeof VISION_MICROAPPS)[number]['id']
