import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { isLocale } from "@/types/locale";
import { LegalPageTemplate } from "@/components/templates/LegalPageTemplate";
import { buildMetadata } from "@/lib/metadata";

export async function generateMetadata(): Promise<Metadata> {
  return buildMetadata({
    routeKey: "legal.privacy",
    locale: "en",
    title: "Privacy policy | Vendrava",
    description: "How Vendrava handles the personal and commercial data of its users and customers.",
  });
}

export default async function Page({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: raw } = await params;
  if (!isLocale(raw) || raw !== "en") notFound();

  return (
    <LegalPageTemplate locale="en" title="Privacy policy" path="legal/privacy" breadcrumbLabel="Privacy" updatedLabel="2026">
      <section>
        <h2>Data controller</h2>
        <p>
          Vendrava is a product operated by SprintMarkt, a digital agency based in Valencia (Spain). For any question
          related to data processing, you can contact the data controller through the contact page.
        </p>
      </section>
      <section>
        <h2>What data we process</h2>
        <p>
          Vendrava processes contact data (name, email, phone, company) that users provide when requesting a demo,
          contacting us, or using the platform, as well as data generated by product usage, such as the history of
          leads, calls and conversations managed by the CRM.
        </p>
      </section>
      <section>
        <h2>Why we process it</h2>
        <p>
          We use this data to provide the service, respond to sales inquiries, improve the product, and comply with
          applicable legal obligations in each market.
        </p>
      </section>
      <section>
        <h2>Who we share it with</h2>
        <p>
          Data may be shared with technology providers required to operate the platform (for example, calling or
          messaging infrastructure), always under confidentiality agreements.
        </p>
      </section>
      <section>
        <h2>User rights</h2>
        <p>
          Users can request access, correction, or deletion of their personal data by writing to our team through the
          contact page.
        </p>
      </section>
    </LegalPageTemplate>
  );
}
