import type { GlossaryItem } from "@/types/content";

export const glossaryEs: GlossaryItem[] = [
  { term: "CRM con IA", definition: "Sistema de gestión de relaciones con clientes que incorpora inteligencia artificial para automatizar tareas comerciales como contestar, calificar y agendar. A diferencia de un CRM tradicional que solo almacena datos, actúa sobre ellos: prioriza contactos, sugiere el siguiente paso y ejecuta interacciones por voz o mensajería. El objetivo es acelerar el ciclo de ventas y reducir el trabajo manual del equipo comercial." },
  { term: "Agente de voz IA", definition: "Software capaz de mantener conversaciones telefónicas por voz en lenguaje natural, entendiendo y respondiendo en tiempo real. Se usa para atender llamadas entrantes, hacer llamadas salientes, calificar leads y agendar citas sin intervención humana constante. Un buen agente de voz suena natural, sigue guiones adaptados al nicho y transfiere a una persona cuando la situación lo requiere." },
  { term: "Speed-to-lead", definition: "Tiempo que transcurre entre que un lead muestra interés y el primer contacto real del equipo comercial. Es un factor determinante de la conversión: responder en el primer minuto en lugar de horas aumenta de forma notable la probabilidad de calificar y cerrar. La automatización con IA permite responder de forma casi inmediata las 24 horas." },
  { term: "Lead scoring", definition: "Método para asignar una puntuación a cada lead según su probabilidad de convertirse en cliente, combinando datos demográficos y de comportamiento. Ayuda al equipo a priorizar los contactos más prometedores y a decidir el momento y canal adecuados. Cuando la IA lo automatiza, la puntuación se actualiza en tiempo real conforme el lead interactúa." },
  { term: "Pipeline", definition: "Representación visual de las oportunidades de venta organizadas por etapas, desde el primer contacto hasta el cierre. Permite ver cuántos negocios hay en cada fase, dónde se estancan y qué ingresos se pueden esperar. Es la herramienta central para pronosticar ventas y detectar cuellos de botella en el proceso comercial." },
  { term: "Sales automation", definition: "Uso de tecnología para ejecutar tareas repetitivas del proceso de ventas sin intervención manual, como envío de seguimientos, registro de datos, calificación o agendado. Su objetivo no es reemplazar al vendedor, sino liberar su tiempo para las conversaciones de mayor valor. Aplicada correctamente, aumenta la consistencia y la velocidad de respuesta." },
  { term: "WhatsApp CRM", definition: "Integración de WhatsApp como canal de comunicación dentro de un CRM, permitiendo gestionar conversaciones, automatizar respuestas y registrar cada interacción junto al resto de datos del cliente. Aprovecha las altas tasas de apertura de la mensajería para calificar y dar seguimiento a leads. Su uso comercial debe respetar las políticas de la plataforma y el consentimiento del contacto." },
  { term: "Llamadas en frío (cold calling)", definition: "Contacto telefónico saliente con personas o empresas que no han solicitado previamente ser contactadas, con el fin de generar interés comercial. Sigue siendo una técnica de prospección vigente, aunque exige buena segmentación y respeto a las normativas aplicables. La automatización con IA permite escalar el volumen manteniendo un discurso adaptado al nicho, siempre bajo control humano." },
  { term: "Transferencia en caliente (warm transfer)", definition: "Paso de una llamada de un agente (humano o IA) a otra persona sin cortar la comunicación, entregando el contexto de la conversación. El cliente no tiene que repetir su información y la transición se siente fluida. Es clave para que la IA derive a un asesor humano en el momento oportuno, por ejemplo cuando el lead está listo para cerrar." },
  { term: "No-show", definition: "Cita o reunión agendada a la que el lead o cliente no asiste ni avisa. Es una fuente importante de pérdida de ingresos y de tiempo comercial desaprovechado. Se reduce con recordatorios automáticos, confirmaciones previas y facilidad para reprogramar, tareas que la IA puede gestionar por voz o mensajería." },
  { term: "Inbound", definition: "Modelo en el que los leads llegan por iniciativa propia, atraídos por contenido, publicidad o recomendaciones, en lugar de ser buscados activamente. El foco está en atender rápido y bien esa demanda entrante para no perder el interés. Un tiempo de respuesta corto es especialmente crítico en inbound, ya que el lead está en un momento de máxima intención." },
  { term: "Outbound", definition: "Modelo en el que el equipo comercial toma la iniciativa de contactar a prospectos que no han pedido información, mediante llamadas, mensajes o correos. Requiere buena segmentación de la lista y un mensaje relevante para cada perfil. Incluye las llamadas en frío y, cuando se automatiza, debe respetar los registros de no-llamar de cada país y la normativa aplicable." },
  { term: "IA conversacional", definition: "Tecnología que permite a un sistema entender el lenguaje humano y sostener un diálogo natural por voz o texto, interpretando la intención más allá de palabras clave. Combina reconocimiento de lenguaje, comprensión del contexto y generación de respuestas coherentes. En ventas se usa para contestar consultas, calificar y agendar como lo haría un asesor entrenado." },
  { term: "Calificación de leads", definition: "Proceso de evaluar si un lead cumple los criterios para convertirse en un cliente potencial real, identificando su necesidad, presupuesto, autoridad de decisión y plazos. Permite descartar contactos no viables y concentrar el esfuerzo donde hay probabilidad de cierre. Puede hacerse mediante preguntas en la conversación, que la IA formula y registra de forma automática." },
  { term: "Seguimiento (follow-up)", definition: "Serie de contactos posteriores al primer acercamiento para mantener vivo el interés de un lead hasta que decide. La mayoría de las ventas requieren varios seguimientos, por lo que la constancia es decisiva. La automatización asegura que ningún lead quede sin atención por olvido, programando recordatorios y mensajes en el momento adecuado." },
  { term: "Tasa de conversión", definition: "Porcentaje de contactos o leads que completan una acción deseada, como agendar una cita o comprar, sobre el total. Es un indicador central para medir la eficacia del proceso comercial en cada etapa. Mejorarla suele depender más de la velocidad y calidad del seguimiento que del volumen de leads." },
  { term: "Growth marketing", definition: "Enfoque de marketing basado en experimentar y medir de forma continua para hacer crecer el negocio a lo largo de todo el embudo, no solo en la captación. Combina datos, iteración rápida y optimización de cada etapa, desde la adquisición hasta la retención. Se apoya en la automatización y la analítica para escalar lo que funciona." },
  { term: "Cumplimiento en llamadas automatizadas", definition: "Conjunto de prácticas para que las llamadas y mensajes automatizados respeten la ley y los derechos de las personas contactadas. Incluye obtener el consentimiento cuando corresponde, informar de forma clara cuando se interactúa con una IA, respetar los registros de no-llamar de cada país y aplicar la normativa de protección de datos aplicable. Un enfoque compliance-first reduce riesgos legales y protege la reputación de la marca." },
];
