// Los componentes de la cabina vienen del laboratorio, que usa lucide-react.
// El CRM ya trae react-icons: se mapean los nombres en vez de añadir otra
// librería de iconos. Misma API de llamada (<Icon size={18} />).
export {
  RiErrorWarningLine as AlertTriangle,
  RiTimeLine as Clock3,
  RiBroadcastLine as Radio,
  RiBroadcastLine as RadioTower,
  RiSettings3Line as Settings2,
  RiCloseLine as X,
  RiPulseLine as Activity,
  RiStackLine as Layers3,
  RiSignalTowerLine as SignalHigh,
  RiTimerLine as TimerReset,
  RiFlowChart as Workflow,
  RiSoundModuleLine as AudioLines,
  RiRhythmLine as AudioWaveform,
  RiBrainLine as BrainCircuit,
  RiCheckLine as Check,
  RiDashboard3Line as Gauge,
  RiSpeedLine as CircleGauge,
  RiCompass3Line as Compass,
  RiVolumeUpLine as Volume2,
  RiVolumeMuteLine as VolumeX,
  RiMicLine as Mic,
  RiMicOffLine as MicOff,
  RiPhoneLine as PhoneOff,
  RiKeyboardLine as Keyboard,
  RiChat3Line as MessageSquareText,
  RiPlayLine as Play,
  RiSendPlaneLine as Send,
  RiSparkling2Line as Sparkles,
  RiFlashlightLine as Zap,
} from 'react-icons/ri'
