import type { GlossaryItem } from "@/types/content";

export const glossaryEn: GlossaryItem[] = [
  { term: "AI CRM", definition: "A customer relationship management system that uses artificial intelligence to automate sales tasks such as answering, qualifying, and booking leads. Unlike a traditional CRM that only stores data, it acts on it: prioritizing contacts, suggesting the next step, and running interactions over voice or messaging. The goal is to speed up the sales cycle and cut the manual workload for the sales team." },
  { term: "AI voice agent", definition: "Software that can hold spoken phone conversations in natural language, understanding and responding in real time. It is used to handle inbound calls, place outbound calls, qualify leads, and book appointments without constant human involvement. A good voice agent sounds natural, follows scripts adapted to the niche, and hands off to a person when the situation calls for it." },
  { term: "Speed-to-lead", definition: "The time between a lead showing interest and the sales team's first real contact. It is a major driver of conversion: responding within the first minute rather than hours markedly increases the chance of qualifying and closing. AI automation makes it possible to respond almost instantly, around the clock." },
  { term: "Lead scoring", definition: "A method for assigning each lead a score based on how likely they are to become a customer, combining demographic and behavioral data. It helps the team prioritize the most promising contacts and choose the right timing and channel. When AI automates it, the score updates in real time as the lead interacts." },
  { term: "Pipeline", definition: "A visual representation of sales opportunities organized by stage, from first contact to close. It shows how many deals sit in each stage, where they stall, and what revenue can be expected. It is the core tool for forecasting sales and spotting bottlenecks in the process." },
  { term: "Sales automation", definition: "The use of technology to run repetitive sales tasks without manual effort, such as sending follow-ups, logging data, qualifying, or scheduling. Its aim is not to replace the salesperson but to free their time for higher-value conversations. Done well, it improves consistency and response speed." },
  { term: "WhatsApp CRM", definition: "The integration of WhatsApp as a communication channel within a CRM, allowing conversations to be managed, replies automated, and every interaction logged alongside the rest of the customer's data. It leverages messaging's high open rates to qualify and follow up with leads. Business use must respect the platform's policies and the contact's consent." },
  { term: "Cold calling", definition: "Outbound phone contact with people or companies that have not previously asked to be reached, aiming to generate commercial interest. It remains a valid prospecting technique, though it requires good targeting and respect for applicable regulations. AI automation can scale the volume while keeping a niche-adapted pitch, always under human oversight." },
  { term: "Warm transfer", definition: "Passing a call from one agent (human or AI) to another person without dropping the line, handing over the context of the conversation. The customer does not have to repeat their information and the transition feels seamless. It is essential for AI to route a lead to a human advisor at the right moment, for example when the lead is ready to close." },
  { term: "No-show", definition: "A scheduled appointment or meeting that the lead or customer fails to attend without notice. It is a major source of lost revenue and wasted sales time. It is reduced through automated reminders, prior confirmations, and easy rescheduling, tasks that AI can handle over voice or messaging." },
  { term: "Inbound", definition: "A model in which leads come on their own initiative, drawn by content, advertising, or referrals, rather than being actively sought out. The focus is on responding quickly and well to that incoming demand so interest is not lost. A short response time is especially critical in inbound, since the lead is at a moment of peak intent." },
  { term: "Outbound", definition: "A model in which the sales team takes the initiative to contact prospects who have not requested information, through calls, messages, or emails. It requires good list segmentation and a message relevant to each profile. It includes cold calling and, when automated, must respect each country's do-not-call registries and applicable regulations." },
  { term: "Conversational AI", definition: "Technology that lets a system understand human language and hold a natural dialogue by voice or text, interpreting intent beyond keywords. It combines language recognition, context understanding, and coherent response generation. In sales it is used to answer questions, qualify, and book much as a trained advisor would." },
  { term: "Lead qualification", definition: "The process of evaluating whether a lead meets the criteria to become a real prospect, identifying their need, budget, decision authority, and timeline. It filters out non-viable contacts and concentrates effort where there is a real chance of closing. It can be done through questions in the conversation, which AI asks and records automatically." },
  { term: "Follow-up", definition: "A series of contacts after the first approach to keep a lead's interest alive until they decide. Most sales require several follow-ups, so consistency is decisive. Automation ensures no lead is left unattended due to oversight, scheduling reminders and messages at the right time." },
  { term: "Conversion rate", definition: "The percentage of contacts or leads who complete a desired action, such as booking an appointment or buying, out of the total. It is a core indicator for measuring how effective the sales process is at each stage. Improving it usually depends more on the speed and quality of follow-up than on lead volume." },
  { term: "Growth marketing", definition: "A marketing approach based on continuous experimentation and measurement to grow the business across the entire funnel, not just acquisition. It combines data, fast iteration, and optimization of every stage, from acquisition to retention. It relies on automation and analytics to scale what works." },
  { term: "Compliance in automated calling", definition: "The set of practices that keep automated calls and messages within the law and respectful of the rights of the people contacted. It includes obtaining consent where required, clearly disclosing when someone is interacting with an AI, honoring each country's do-not-call registries, and applying the applicable data protection regulations. A compliance-first approach reduces legal risk and protects the brand's reputation." },
];
