// Barrel único del catálogo (docs/plataforma-abierta/07-MICROAPPS.md). Cada app
// se auto-registra al importarse; añadir una microapp = crear su archivo y
// listarlo aquí. Lo importa el arranque de providers (API y worker).
import './companyResearch360'
import './businessOpportunityRadar'
import './callPrep'
import './prospectDiagnosis'
import './podcastGuestResearch'
import './voiceOfCustomer'
import './contentMultiplier'
import './modelPicker'
import './cinemaConcepts'
import './openPlatformWave1'
import './growthSalesPackA'
import './growthSalesPackB'
import './adsGrowthPack'
import './contentAuthorityPack'
import './studioMediaPack'
import './studioOpsPack49to66'
import './revenueAgencyPackA'
import './revenueAgencyPackB'
import './intelligenceGrowthPack21to40'
import './wave2ContentMediaPack'
import './wave2DataAiOpsPack'
