/** Catálogo estable y fixtures ejecutables de la segunda ola Revenue + Agency OS. */
export const REVENUE_AGENCY_MICROAPP_IDS = {
  1: 'opportunity-close-plan',
  2: 'mutual-action-plan',
  3: 'churn-risk-detector',
  4: 'renewal-prep',
  5: 'verifiable-case-study',
  6: 'prompt-model-lab',
  7: 'client-margin-auditor',
  8: 'client-onboarding-copilot',
  9: 'end-to-end-experience-auditor',
  10: 'personalized-demo-builder',
  11: 'crm-completeness-inspector',
  12: 'pipeline-coach',
  13: 'business-case-builder',
  14: 'roi-calculator',
  15: 'poc-designer',
  16: 'qbr-prep',
  17: 'client-approval-center',
  18: 'next-microapp-recommender',
  19: 'monthly-client-report',
  20: 'client-profitability-calculator',
} as const

export const REVENUE_AGENCY_INPUT_FIXTURES: Record<(typeof REVENUE_AGENCY_MICROAPP_IDS)[keyof typeof REVENUE_AGENCY_MICROAPP_IDS], unknown> = {
  'opportunity-close-plan': { opportunityId: 'opp-1', targetCloseDate: '2026-10-30', constraints: 'Legal necesita cinco días.' },
  'mutual-action-plan': { opportunityId: 'opp-1', buyerOutcome: 'Activar 20 usuarios', targetGoLiveDate: '2026-11-15', knownDependencies: 'SSO y DPA.' },
  'churn-risk-detector': { accountId: 'acc-1', reviewWindowDays: 90, contractedOutcome: 'Reducir CPL un 20%', suppliedSignals: 'Dos sesiones canceladas.' },
  'renewal-prep': { accountId: 'acc-1', renewalDate: '2026-12-01', currentContractCents: 240000, contractScope: 'Plan anual de 20 usuarios', commercialConstraints: 'IPC máximo 4%.' },
  'verifiable-case-study': { accountId: 'acc-1', verifiedOutcomes: 'CPL: 42€ antes, 31€ después; dashboard exportado 2026-08-01.', customerQuotes: '“Ahora vemos el origen de cada lead” — entrevista aprobada.', allowedClaims: 'Reducción observada del CPL; trazabilidad de leads.', audience: 'Equipos de growth B2B' },
  'prompt-model-lab': { prompt: 'Clasifica el ticket y devuelve JSON.', testCases: [{ id: 't1', input: 'No puedo entrar', expected: 'access' }], candidateProviders: ['deepseek'], rubric: 'Exactitud de etiqueta y JSON válido', maxCostCentsPerRun: 10 },
  'client-margin-auditor': { accountId: 'acc-1', daysBack: 90, recognizedRevenueCents: 300000, laborCostCents: 90000, otherDirectCostCents: 15000 },
  'client-onboarding-copilot': { customerName: 'Acme', contractScope: 'Implantación CRM y agentes', kickoffNotes: 'Go-live en noviembre. Responsable Ana.', requiredIntegrations: 'HubSpot, Slack', targetGoLiveDate: '2026-11-15' },
  'end-to-end-experience-auditor': { objective: 'Reservar demo', audience: 'COO de SaaS', adExperience: 'Anuncio promete auditoría gratis.', landingExperience: 'Formulario de 8 campos.', followUpExperience: 'Email llega en 20 minutos.', meetingExperience: 'Demo genérica.', observedMetrics: 'CTR 1.2%, CVR landing 2.1%, show rate 58%.' },
  'personalized-demo-builder': { accountId: 'acc-1', meetingGoal: 'Validar encaje técnico', productCapabilities: 'Routing BYOK, microapps, auditoría', knownPain: 'Costes opacos y diez herramientas', demoMinutes: 30 },
  'crm-completeness-inspector': { scope: 'pipeline', opportunityId: 'opp-1', daysStale: 14 },
  'pipeline-coach': { horizonDays: 30, ownerId: '', targetCents: 500000, coachingFocus: 'Cobertura y siguiente paso' },
  'business-case-builder': { problem: 'Preparación manual de campañas', affectedTeams: 'Growth y ventas', currentCostEvidence: '80 horas/mes a 40€/h', proposedSolution: 'Vendrava Agency OS', implementationCostCents: 120000, annualSubscriptionCents: 600000, expectedBenefits: '40 horas/mes recuperadas; menos errores', assumptions: 'Adopción del 70%' },
  'roi-calculator': { currency: 'EUR', horizonMonths: 12, oneTimeCostCents: 120000, recurringMonthlyCostCents: 50000, monthlyBenefitCents: 180000, rampMonths: 3, confidencePct: 70 },
  'poc-designer': { hypothesis: 'El routing reduce coste manteniendo calidad', scope: '200 ejecuciones de clasificación', availableData: 'Dataset anonimizado con 200 casos', durationDays: 21, stakeholders: 'CTO, RevOps, DPO', constraints: 'Datos solo UE' },
  'qbr-prep': { accountId: 'acc-1', periodStart: '2026-05-01', periodEnd: '2026-07-31', contractedOutcomes: 'Reducir CPL y mejorar velocidad de respuesta', suppliedResults: 'CPL -18%; respuesta de 2h a 12m', roadmapContext: 'Añadir WhatsApp en Q4' },
  'client-approval-center': { clientName: 'Acme', campaignName: 'Q4 Pipeline', items: [{ id: 'asset-1', kind: 'ad', title: 'Anuncio A', version: 'v3', summary: 'Nuevo hook', localRef: 'asset:asset-1', checks: ['claim aprobado'] }], approvalDeadline: '2026-10-01', reviewerInstructions: 'Aprobar o pedir cambios por elemento.' },
  'next-microapp-recommender': { goal: 'Preparar renovación', entityType: 'account', availableData: ['accounts.read', 'pipeline.read', 'costs.read'], preferredCategory: 'success', maxSuggestions: 5 },
  'monthly-client-report': { accountId: 'acc-1', month: '2026-07', objectives: 'Más demos cualificadas', suppliedResults: '34 demos, 21 cualificadas', completedWork: 'Nueva landing y secuencia', nextExperiments: 'Test de prueba social' },
  'client-profitability-calculator': { currency: 'EUR', monthlyFeeCents: 250000, expectedProviderCostCents: 40000, expectedLaborHours: 35, laborCostPerHourCents: 3000, otherMonthlyCostsCents: 10000, contingencyPct: 10, targetMarginPct: 35, scenarios: [{ name: 'crecimiento', feeDeltaPct: 15, volumeDeltaPct: 25 }] },
}
